#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppTesting.Resource", IsApplication=true)]

namespace AppTesting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int imgMovie = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int imgMovieDetail = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int imgTopMovie = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int listNews = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int listTop = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int lista = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int listaTop = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int txtMovieGenre = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int txtMovieGenreDetail = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int txtMovieName = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int txtMovieNameDetail = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int txtMovieOverviewDetail = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int txtMovieRateDetail = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtMovieRealNameDetail = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int txtMovieRelease = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int txtMovieReleaseDetail = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int txtTitulo = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int txtTitulo2 = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int txtTopMovieName = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int txtTopMovieRate = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int txtTopMovieRelease = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Details = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MovieItemAdapter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TopMovieItemAdapter = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int TopMovies = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int UpcomingMovies = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
